### ISSUE TITLE
Solve 1646C quoestion of codeforces

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#1]
Problem Link - https://codeforces.com/problemset/problem/1646/C
Problem rating: 1500

To make the PR make the file Problems folder & write the file name as a like 1646C - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :
- [x] Appropriate title of PR
- [x]  Making another branch with an appropriate name.
- [x]  Comment on file in the top with the link of the question

**Comment by Arpitgupta1014** [comment]
Hi @aayush0331, Can I work on this issue
