### ISSUE TITLE
Solve Merge k Sorted Lists-Leetcode

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#13]
Problem Link - https://leetcode.com/problems/merge-k-sorted-lists/
Platform - Leetcode
Difficulty - Hard

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation. CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

-> An appropriate title for PR
-> Making another file with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding

**Comment by Arpitgupta1014** [comment]
Hey, @aayush0331 Can I work on this issue?
