### ISSUE TITLE
Solve First Missing positive-Leetcode

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#15]
Problem Link - https://leetcode.com/problems/first-missing-positive/
Platform - Leetcode
Difficulty - Hard

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation. CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

-> An appropriate title for PR
-> Making another file with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding

**Comment by Vivek2213** [comment]
sir , i want to work on this issue . so , please assign me this task.
