### ISSUE TITLE
Largest Rectangle in Histogram-Leetcode

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#16]
Problem Link - https://leetcode.com/problems/largest-rectangle-in-histogram/
Platform - Leetcode
Difficulty - Hard

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation. CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

-> An appropriate title for PR
-> Making another file with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding

**Comment by amansingh854** [comment]
Hey @aayush0331, can I work on this issue?
