### ISSUE TITLE
Solve 1574B - Combinatorics Homework

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#19]
Problem Link -https://codeforces.com/problemset/problem/1574/B
Problem rating: 1100
Tags - combinatorics greedy math

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

-> Appropriate title of PR
-> Making another branch with an appropriate name.
-> Comment on file in the top with the link of the question
Happy Coding 👍

**Comment by adi-wav** [comment]
I would like to solve this issue.

**Comment by ashishpetwal** [comment]
I have solved this issue may I submit pr

**Comment by adityaomar3** [comment]
I think I am fimiliar with this. I can solve this one

**Comment by singhAman05** [comment]
sir @aayush0331 can i work on tis problem

**Comment by aayush0331** [comment]
Nice job @adi-wav
