### ISSUE TITLE
Solution for CSES - Increasing Array

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#21]
Problem Link - https://cses.fi/problemset/task/1094
Tag - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension. OR whatever but in the same folder as mentioned

Make sure this before making PR regarding it :

-> Appropriate title of PR
-> Making another branch with an appropriate name.
-> Comment on file in the top with the link of the question

**Comment by adityaomar3** [comment]
I am familiar with this issue. I would like to solve it.
