### ISSUE TITLE
Solve power set

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#25]
Problem Link - https://practice.geeksforgeeks.org/problems/power-set4302/1
Tag - bit manipulation, implementation
Platform - Gfg
Difficulty - Easy
To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

An appropriate title for PR
Making another file with an appropriate name.
Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by Arpitgupta1014** [comment]
Hey @aayush0331 , Can I work on this issue.
