### ISSUE TITLE
Solve 1579E2 - Array Optimization by Deque

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#28]
Problem Link - https://codeforces.com/problemset/problem/1579/E2
Problem rating: 1700
Tag - greedy, implementation
Platform - Codeforces
Difficulty - Hard

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

 - Appropriate title of PR
 - Making another branch with an appropriate name.
 - Comment on file in the top with the link of the question
Happy Coding 👍

**Comment by Arpitgupta1014** [comment]
Hey @aayush0331 , Can I work on this issue.
