### ISSUE TITLE
1335D- Anti-Sudoku

### ISSUE THREAD

**Issue by aayush0331** [aayush0331/Competitive-Programming#31]
Problem Link - https://codeforces.com/problemset/problem/1335/d
Problem rating: 1300
Tag -  constructive algorithms, implementation
Platform - Codeforces
Difficulty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

Appropriate title of PR
Making another file with an appropriate name.
Comment on file in the top with the link of the question
Happy Coding 👍

**Comment by Arpitgupta1014** [comment]
Hey @aayush0331 , Can I work on this issue
